### ISSUE TITLE
eta_formatted and duration_formatted number padding

### ISSUE THREAD

**Issue by dan2600** [AndiDittrich/Node.CLI-Progress#60]
Would be great for the eta_formatted and duration_formatted values to be padded. Without padding it causes a lot of jumping of the bars when displaying single digit numbers.

**Comment by AndiDittrich** [comment]
not as default format - you can use a custom formatter so solve the issue.

additionally i can may add custom filter functions for all placeholder

**Comment by dan2600** [comment]
Hi Andi, thanks for your response! I'm able to pad the percentage by using a simple function in the format

`('00'+'{percentage}').slice(-2);`

However, ETA_formatted and duration_formated come in as full string (like 24m5s or 5m45s, etc). And without a complex regex it would be difficult to format them  with number pads.

An option when invoking a new multibar to optionally set a number of digits to pad numbers for formatted outputs would be amazing. If you accept pull requests on this great library I would be happy to try to help when I have some time.

**Comment by AndiDittrich** [comment]
It is quite easy to implement but i'm looking for a more generic solution (especially it should not break the existing behaviour)

**Comment by AndiDittrich** [comment]
i've just added two options to the master branch:

- `autopadding` (type: boolean) - add padding chars to formatted time and percentage to force fixed width (default: false) - Note: handled standard format functions!
- `autopaddingChar` (type: string) - the character sequence used for autopadding (default: "   ") - Note: due to performance optimizations this value requies a length of 3 identical chars

additionally, you can use custom element format callbacks to override the default rendering:

- `formatBar` (type: function) - a custom bar formatter function which renders the bar-element (default: [format-bar.js](lib/format-bar.js))
- `formatTime` (type: function) - a custom timer formatter function which renders the formatted time elements like `eta_formatted` and `duration-formatted` (default: [format-time.js](lib/format-time.js))
- `formatValue` (type: function) - a custom value formatter function which renders all other values (default: [format-value.js](lib/format-value.js))

**Comment by dan2600** [comment]
Amazing Andi! I'll try it out. I'm using your library for CLI batch video recorder, and it's working great!!!!
